version: '3'

volumes:
  nextcloud:
  nextcloud_data:

services:
  nextcloud:
    build: ./nextcloud
    image: munsen/nextcloud:stable
    ports:
      - "8080:80"
    restart: always
    container_name: nextcloud
    network_mode: bridge
    volumes:
      - html:/var/www/html
      - /mnt/storage/nextcloud/data:/var/www/html/data
      - /mnt/storage/transmission:/mnt/transmission
volumes:
   html:
