version: '3'

volumes:
  nextcloud:
  nextcloud_data:

services:
  nextcloud:
    build: ./nextcloud
    image: munsen/nextcloud:stable
    ports:
      - "8080:80"
    restart: always
    container_name: nextcloud
    network_mode: bridge
    volumes:
      - /mnt/md0/nextcloud:/var/www/html 
      - /mnt/md0/transmission:/mnt/transmission
